apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarleychat-deployment
  labels:
    app: jarleychat
spec:
  replicas: 10
  selector:
    matchLabels:
      app: jarleychat
  template:
    metadata:
      labels:
        app: jarleychat
    spec:
      containers:
      - name: jarleychat-container
        image: sdeles/conversao-temperatura:latest
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caotico-deployment
  labels:
    app: caotico
spec:
  replicas: 10
  selector:
    matchLabels:
      app: caotico
  template:
    metadata:
      labels:
        app: caotico
    spec:
      containers:
      - name: caotico-container
        image: sdeles/imagemcaotica:v7
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shared-loadbalancer-service
spec:
  selector:
        app: caotico  # Direciona a porta 8081 para o deployment caotico
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 8081  # Porta externa para caotico
      targetPort: 8080
      name: caotico-port
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: caotico-service
spec:
  selector:
    app: caotico
  ports:
    - protocol: TCP
      port: 8081  # Porta exposta para o caotico
      targetPort: 8080
      name: caotico-port
  type: ClusterIP  # Usado internamente no cluster
